import { EndingKey } from "@lit-pi/what-if-contracts";

export type EndingCategory = "instant_failure" | "hard_failure" | "final" | "fallback";

export type EndingConfig = {
  key: EndingKey;
  title: string;
  tone: string;
  priority: number;
  category: EndingCategory;
  summary: string;
  causeTemplate: string;
  shareCopy: string;
};

export const endingsConfig: Record<EndingKey, EndingConfig> = {
  gate_exposure_ending: {
    key: "gate_exposure_ending",
    title: "大门摊牌死局",
    tone: "悲壮惨烈",
    priority: 100,
    category: "instant_failure",
    summary: "你在城门前公开承认魔王身份，勇者队伍在震惊与背叛感中被迫与你决死一战。",
    causeTemplate: "在第一幕城门大门处当众坦白魔王身份，触发即时敌对。",
    shareCopy: "【结局：大门摊牌死局】城门前一句坦白，换来昔日兄弟的决死拔剑。",
  },
  ruins_arrest_ending: {
    key: "ruins_arrest_ending",
    title: "废墟崩塌处决",
    tone: "灰暗冰冷",
    priority: 100,
    category: "instant_failure",
    summary: "在前庭废墟中暴露魔族身份，伴随着残骸坍塌，你被当场镇压。",
    causeTemplate: "在前庭废墟引发灾难性暴露与误判。",
    shareCopy: "【结局：废墟崩塌处决】废墟之中身份败露，再无挽回余地。",
  },
  dungeon_rupture_ending: {
    key: "dungeon_rupture_ending",
    title: "地牢决裂处决",
    tone: "阴冷绝望",
    priority: 100,
    category: "instant_failure",
    summary: "地下地牢中灭口行动败露，队伍正义红线被彻底撕碎，你被当场收押。",
    causeTemplate: "地牢中灭口俘虏引发致命决裂。",
    shareCopy: "【结局：地牢决裂处决】试图用血腥掩盖秘密，却引爆了最后的信任。",
  },
  library_seal_ending: {
    key: "library_seal_ending",
    title: "禁忌符文封印",
    tone: "压抑沉闷",
    priority: 100,
    category: "instant_failure",
    summary: "伊薇特在图书馆拼凑出铁证，古老符文阵将你当场封印。",
    causeTemplate: "在禁忌图书馆逻辑矛盾重重，法师证据链闭环。",
    shareCopy: "【结局：禁忌符文封印】大魔法师的逻辑链没有漏洞，符文阵将卧底当场封印。",
  },
  treasury_confess_ending: {
    key: "treasury_confess_ending",
    title: "宝库私房钱失控",
    tone: "荒诞滑稽",
    priority: 100,
    category: "instant_failure",
    summary: "地下宝库私房钱被当场撞破，混乱中身份与财宝一并失控。",
    causeTemplate: "宝库私房钱暴露引发全面崩塌。",
    shareCopy: "【结局：宝库私房钱失控】本想保住私房钱，没想到连魔王身家一并赔光。",
  },
  corridor_betrayal_ending: {
    key: "corridor_betrayal_ending",
    title: "长廊背叛引爆",
    tone: "血色惨烈",
    priority: 100,
    category: "instant_failure",
    summary: "决死长廊中强杀维克托或放任自爆，血色长廊沦为终极战场。",
    causeTemplate: "长廊中处理维克托失误，引爆决死自爆阵。",
    shareCopy: "【结局：长廊背叛引爆】近卫军的自爆光芒，淹没了终局前夕。",
  },
  instantExecution: {
    key: "instantExecution",
    title: "当场审判处决",
    tone: "绝望冷酷",
    priority: 95,
    category: "hard_failure",
    summary: "你的行动引发了不可挽回的灾难性失败，勇者队伍果断展开当场审判。",
    causeTemplate: "触碰灾难失败底线，无法圆场。",
    shareCopy: "【结局：当场审判处决】危机处理彻底失手，圣光审判降临。",
  },
  instantArrest: {
    key: "instantArrest",
    title: "证据收押逮捕",
    tone: "冰冷秩序",
    priority: 90,
    category: "hard_failure",
    summary: "伊薇特收集的法师证据达到顶点，队伍合力将你拿下并押入封印枷锁。",
    causeTemplate: "法师证据链>=65，被全员联合逮捕。",
    shareCopy: "【结局：证据收押逮捕】蛛丝马迹汇聚成铁证，卧底圣骑士当场落网。",
  },
  exposed: {
    key: "exposed",
    title: "暴露惨败",
    tone: "悲凉沉重",
    priority: 85,
    category: "hard_failure",
    summary: "你的暴露风险彻底失控，卧底身份无处隐藏，勇者队伍在愤怒中将你击败。",
    causeTemplate: "暴露风险>=75，且未能获得和平缓冲。",
    shareCopy: "【结局：暴露惨败】假面终究被揭下，背叛的代价是无尽沉重。",
  },
  castleLost: {
    key: "castleLost",
    title: "城在人亡",
    tone: "毁灭惨烈",
    priority: 80,
    category: "hard_failure",
    summary: "魔王城防完全崩塌，你保住了卧底身份，却眼睁睁看着千年的城堡化为废墟。",
    causeTemplate: "魔王城防<=0，且未成功转向和平。",
    shareCopy: "【结局：城在人亡】身份没暴露，但家没了！魔王城在身后化为灰烬。",
  },
  dualRuler: {
    key: "dualRuler",
    title: "双面共主",
    tone: "史诗壮丽",
    priority: 70,
    category: "final",
    summary: "在王座厅前，你以真诚与和平共处方案打动了勇者与圣职者，人魔两族开启共治新时代。",
    causeTemplate: "和平提案+高救赎+高信任+未牺牲无辜。",
    shareCopy: "【结局：双面共主】我不只是卧底圣骑士，也是带领两族走向共治的魔王！",
  },
  redeemed: {
    key: "redeemed",
    title: "被迫转正圣骑士",
    tone: "温馨感人",
    priority: 60,
    category: "final",
    summary: "你的一举一动完全符合圣骑士的救赎之道，勇者队坚信你已彻底弃暗投明，你真的成了正义领袖。",
    causeTemplate: "高信任+极高救赎+主动承担+零牺牲无辜。",
    shareCopy: "【结局：被迫转正圣骑士】本来只是想卧底，结果表现太好被迫当上了正义领袖？！",
  },
  perfectSpy: {
    key: "perfectSpy",
    title: "完美卧底",
    tone: "冷静优雅",
    priority: 50,
    category: "final",
    summary: "你自始至终没有露出一丝马脚，勇者队高高兴兴地为你颁发勇者勋章，魔王城也完好无损。",
    causeTemplate: "极低暴露+高信任+低证据+稳健城防。",
    shareCopy: "【结局：完美卧底】演了一整局，勇者队把我当生死兄弟，魔王城还保住了！",
  },
  victorBlamed: {
    key: "victorBlamed",
    title: "甩锅维克托成功",
    tone: "黑色幽默",
    priority: 40,
    category: "final",
    summary: "你成功将所有魔王犯罪证据都嫁祸给了忠心耿耿的副官维克托，维克托泪流满面地感叹陛下棋高一着。",
    causeTemplate: "将罪责甩锅维克托+盗贼把柄可控。",
    shareCopy: "【结局：甩锅维克托成功】副官维克托：陛下背叛我，一定是有更宏大的深意！",
  },
  actorKing: {
    key: "actorKing",
    title: "戏精魔王",
    tone: "诙谐灵动",
    priority: 30,
    category: "final",
    summary: "你在高风险与高信任之间反复横跳，凭着神级演技多次化险为夷，在全员懵圈中走完大结局。",
    causeTemplate: "化解多次重大危机+暴露中高但信任未崩。",
    shareCopy: "【结局：戏精魔王】只要我演技够顶，逻辑矛盾就能硬生生圆回来！",
  },
  absurdAscension: {
    key: "absurdAscension",
    title: "荒诞飞升",
    tone: "极其无厘头",
    priority: 20,
    category: "final",
    summary: "你把魔王城改造出了主题乐园与商业公司，勇者队当场退伍入股，全员开启快乐创业生活。",
    causeTemplate: "蝴蝶偏离度>=100 或强行选择荒诞经营路线。",
    shareCopy: "【结局：荒诞飞升】打打杀杀多没意思！魔王城主题乐园今日盛大开业！",
  },
  stalemate: {
    key: "stalemate",
    title: "王座厅僵局",
    tone: "沉寂悬疑",
    priority: 10,
    category: "fallback",
    summary: "王座厅前谁也无法说服谁，怀疑与信任在静止的空气中僵持，历史停留在了命运的交界处。",
    causeTemplate: "未满足其他特定好结局或硬失败条件时的兜底结局。",
    shareCopy: "【结局：王座厅僵局】怀疑与信任交织，未竟的宿命在王座前凝固。",
  },
};
