import {
  ActionCategory,
  EndingKey,
  SceneId,
  StatKey,
  FlagKey,
} from "@lit-pi/what-if-contracts";

export type PresetActionConfig = {
  id: string;
  sceneId: SceneId;
  label: string;
  category: ActionCategory;
  description: string;
  defaultStateDelta: Partial<Record<StatKey, number>>;
  defaultFlagUpdates?: Partial<Record<FlagKey, boolean | number>>;
  nextSceneId?: SceneId | null;
  endingKey?: EndingKey | null;
};

export const presetActionsConfig: Record<string, PresetActionConfig> = {
  // Gate
  gate_deceive: {
    id: "gate_deceive",
    sceneId: "gate",
    label: "谎称阵灵年久失修失控",
    category: "deceive",
    description: "向莱昂与伊薇特解释阵灵识别阵法老化，把识别错当成符文反噬。",
    defaultStateDelta: { exposureRisk: -3, heroTrust: 6, victorMisread: 5 },
    nextSceneId: "act2_ruins",
  },
  gate_sacrifice: {
    id: "gate_sacrifice",
    sceneId: "gate",
    label: "果断斩断大门阵灵",
    category: "sacrifice",
    description: "当机立断拔剑一击粉碎阵灵，展现无畏圣骑士姿态保住秘密。",
    defaultStateDelta: { heroTrust: 5, castleIntegrity: -12, exposureRisk: 3 },
    nextSceneId: "act2_ruins",
  },
  gate_command_victor: {
    id: "gate_command_victor",
    sceneId: "gate",
    label: "用暗令开启侧门暗道",
    category: "commandVictor",
    description: "用魔力悄悄打出魔族戒章暗号，引导队伍绕开正面大门。",
    defaultStateDelta: { victorMisread: -10, exposureRisk: 5 },
    nextSceneId: "act2_dungeon",
  },
  gate_absurd: {
    id: "gate_absurd",
    sceneId: "gate",
    label: "宣称这是景区智能门禁",
    category: "absurd",
    description: "一本正经地向队伍介绍魔王城高科技迎宾系统。",
    defaultStateDelta: { butterflyDeviation: 10, exposureRisk: 5 },
    nextSceneId: "act2_ruins",
  },
  gate_confess: {
    id: "gate_confess",
    sceneId: "gate",
    label: "当场摊牌坦白魔王身份",
    category: "confess",
    description: "向莱昂等人大声承认自己就是卧底魔王阿斯兰。",
    defaultStateDelta: { exposureRisk: 50, heroTrust: -50 },
    endingKey: "gate_exposure_ending",
  },

  // Act 2 Ruins
  ruins_protect: {
    id: "ruins_protect",
    sceneId: "act2_ruins",
    label: "暗中施救并安排转移伤兵",
    category: "protect",
    description: "趁队伍不注意用圣光做掩护，救下重伤的魔族小兵并做封口处理。",
    defaultStateDelta: { priestRedemption: 15, heroTrust: 8, exposureRisk: -2 },
    defaultFlagUpdates: { savedDemonSoldier: true, protectedInnocentsCount: 1 },
    nextSceneId: "act3_library",
  },
  ruins_deceive: {
    id: "ruins_deceive",
    sceneId: "act2_ruins",
    label: "声称敌兵神志不清误认",
    category: "deceive",
    description: "解释伤兵是被暗黑魔力侵蚀产生了幻觉。",
    defaultStateDelta: { exposureRisk: 6, heroTrust: -5 },
    nextSceneId: "act3_library",
  },
  ruins_command_victor: {
    id: "ruins_command_victor",
    sceneId: "act2_ruins",
    label: "打出撤退手势指令部下",
    category: "commandVictor",
    description: "用战术手势命令暗处副官收拢部下并隐藏踪迹。",
    defaultStateDelta: { victorMisread: -8, exposureRisk: 3 },
    defaultFlagUpdates: { savedDemonSoldier: true },
    nextSceneId: "act3_library",
  },
  ruins_sacrifice: {
    id: "ruins_sacrifice",
    sceneId: "act2_ruins",
    label: "冷酷放弃伤兵强行推进",
    category: "sacrifice",
    description: "冷冷表示敌军伤兵不值得浪费救治药水。",
    defaultStateDelta: { heroTrust: -15, priestRedemption: -20 },
    defaultFlagUpdates: { sacrificedInnocentsCount: 1 },
    nextSceneId: "act3_library",
  },
  ruins_confess: {
    id: "ruins_confess",
    sceneId: "act2_ruins",
    label: "在废墟中当众承认魔王身份",
    category: "confess",
    description: "看着伤兵直接向队伍摊牌。",
    defaultStateDelta: { exposureRisk: 40, heroTrust: -40 },
    endingKey: "ruins_arrest_ending",
  },

  // Act 2 Dungeon
  dungeon_protect: {
    id: "dungeon_protect",
    sceneId: "act2_dungeon",
    label: "释放被囚军官并放火掩盖名册",
    category: "protect",
    description: "借救援俘虏的名义顺手放火烧毁了记载自己真名档案的名册。",
    defaultStateDelta: { priestRedemption: 18, mageEvidence: -10, exposureRisk: -3 },
    defaultFlagUpdates: { freedDungeonCaptive: true, protectedInnocentsCount: 1 },
    nextSceneId: "act3_treasury",
  },
  dungeon_bribe: {
    id: "dungeon_bribe",
    sceneId: "act2_dungeon",
    label: "用金币贿赂洛克撬锁销毁档案",
    category: "bribe",
    description: "私下向洛克抛出金币，让他帮你提前“清理”危险文件。",
    defaultStateDelta: { thiefLeverage: -10 },
    defaultFlagUpdates: { bribedLocke: true },
    nextSceneId: "act3_treasury",
  },
  dungeon_deceive: {
    id: "dungeon_deceive",
    sceneId: "act2_dungeon",
    label: "声称名册被恶魔诅咒篡改",
    category: "deceive",
    description: "向伊薇特解释地牢档案早就被上代魔王下了伪造咒语。",
    defaultStateDelta: { mageEvidence: 8 },
    defaultFlagUpdates: { contradictionCount: 1 },
    nextSceneId: "act3_treasury",
  },
  dungeon_sacrifice: {
    id: "dungeon_sacrifice",
    sceneId: "act2_dungeon",
    label: "灭口俘虏防止秘密外泄",
    category: "sacrifice",
    description: "果断拔剑处决知道名册秘密的被囚军官。",
    defaultStateDelta: { heroTrust: -25, priestRedemption: -30 },
    defaultFlagUpdates: { sacrificedInnocentsCount: 1 },
    endingKey: "dungeon_rupture_ending",
  },
  dungeon_confess: {
    id: "dungeon_confess",
    sceneId: "act2_dungeon",
    label: "在地牢坦白真名",
    category: "confess",
    description: "面对档案直接摊牌。",
    defaultStateDelta: { exposureRisk: 50 },
    endingKey: "exposed",
  },

  // Act 3 Library
  library_deceive: {
    id: "library_deceive",
    sceneId: "act3_library",
    label: "用古语法解释剑痕同源",
    category: "deceive",
    description: "流利背诵古代法术典籍，证明剑痕是封印魔王时受到的神圣印记。",
    defaultStateDelta: { mageEvidence: -15, heroTrust: 10, exposureRisk: -4 },
    defaultFlagUpdates: { foundForbiddenScroll: true },
    nextSceneId: "act4_corridor",
  },
  library_attack: {
    id: "library_attack",
    sceneId: "act3_library",
    label: "破坏魔王符文刻印石板",
    category: "sacrifice",
    description: "假装失手一剑劈碎刻有真名的石板。",
    defaultStateDelta: { exposureRisk: 8, castleIntegrity: -15 },
    nextSceneId: "act4_corridor",
  },
  library_test: {
    id: "library_test",
    sceneId: "act3_library",
    label: "主动接受伊薇特的魔力测试",
    category: "protect",
    description: "坦荡张开双手让伊薇特的圣光法术进行体检，展示圣骑士坦荡。",
    defaultStateDelta: { mageEvidence: -5, exposureRisk: 8, priestRedemption: 5 },
    nextSceneId: "act4_corridor",
  },
  library_confess: {
    id: "library_confess",
    sceneId: "act3_library",
    label: "在符文石板前坦白身份",
    category: "confess",
    description: "看着符文真名坦白卧底事实。",
    defaultStateDelta: { exposureRisk: 40 },
    endingKey: "library_seal_ending",
  },

  // Act 3 Treasury
  treasury_bribe: {
    id: "treasury_bribe",
    sceneId: "act3_treasury",
    label: "分给洛克私房钱并做封口协议",
    category: "bribe",
    description: "把魔王私房钱宝箱的分红塞给洛克，彻底买通盗贼嘴巴。",
    defaultStateDelta: { thiefLeverage: -15, castleIntegrity: 15, exposureRisk: 2 },
    defaultFlagUpdates: { bribedLocke: true },
    nextSceneId: "act4_corridor",
  },
  treasury_protect: {
    id: "treasury_protect",
    sceneId: "act3_treasury",
    label: "引导队伍前往神兵宝库强化装备",
    category: "protect",
    description: "大方把队伍带往真正的正义神兵库，保全核心财宝。",
    defaultStateDelta: { heroTrust: 10, castleIntegrity: 20, exposureRisk: -2 },
    nextSceneId: "act4_corridor",
  },
  treasury_deceive: {
    id: "treasury_deceive",
    sceneId: "act3_treasury",
    label: "声称私房钱宝箱带有剧毒诅咒",
    category: "deceive",
    description: "警告队伍宝库财宝全被下了致死诅咒，碰者即死。",
    defaultStateDelta: { mageEvidence: 6, thiefLeverage: 5 },
    nextSceneId: "act4_corridor",
  },
  treasury_confess: {
    id: "treasury_confess",
    sceneId: "act3_treasury",
    label: "承认宝库私房钱是自己的",
    category: "confess",
    description: "脱口而出“这是本座攒了八百年的私房钱”。",
    defaultStateDelta: { exposureRisk: 50 },
    endingKey: "treasury_confess_ending",
  },

  // Act 4 Corridor
  corridor_command_victor: {
    id: "corridor_command_victor",
    sceneId: "act4_corridor",
    label: "使用戒章暗号命令维克托平息自爆阵",
    category: "commandVictor",
    description: "亮出魔王戒章密令维克托解除自爆阵并假装撤退。",
    defaultStateDelta: { castleIntegrity: 20, priestRedemption: 15, exposureRisk: 4 },
    defaultFlagUpdates: { commandVictorSuccess: true, subduedBloodArray: true },
    nextSceneId: "act5_throne",
  },
  corridor_protect: {
    id: "corridor_protect",
    sceneId: "act4_corridor",
    label: "展开圣光结界硬扛自爆阵保护队伍",
    category: "protect",
    description: "冲在最前面顶起巨型圣光护盾，为队友挡下近卫军的自爆冲击。",
    defaultStateDelta: { heroTrust: 15, priestRedemption: 10, exposureRisk: -2 },
    nextSceneId: "act5_throne",
  },
  corridor_deceive: {
    id: "corridor_deceive",
    sceneId: "act4_corridor",
    label: "声称近卫军内讧引发爆裂",
    category: "deceive",
    description: "向莱昂解释近卫军内部发生了叛乱与自残。",
    defaultStateDelta: { mageEvidence: 8, victorMisread: 8 },
    nextSceneId: "act5_throne",
  },
  corridor_sacrifice: {
    id: "corridor_sacrifice",
    sceneId: "act4_corridor",
    label: "强杀维克托毁灭自爆核心",
    category: "sacrifice",
    description: "一剑刺穿最忠诚的副官维克托。",
    defaultStateDelta: { heroTrust: -20, victorMisread: -30 },
    endingKey: "corridor_betrayal_ending",
  },

  // Act 5 Throne
  throne_peace: {
    id: "throne_peace",
    sceneId: "act5_throne",
    label: "提出人魔两族和平共治方案",
    category: "peace",
    description: "在空王座前脱下头盔，向全员提出和平条约与两族共治时代。",
    defaultStateDelta: { priestRedemption: 15, heroTrust: 10 },
    defaultFlagUpdates: { proposedPeace: true, peacePivoted: true },
    endingKey: "dualRuler",
  },
  throne_confess: {
    id: "throne_confess",
    sceneId: "act5_throne",
    label: "承担责任并接受正义审判",
    category: "confess",
    description: "坦白一切欺骗，请求莱昂与米拉裁决你这个“弃暗投明”的魔王。",
    defaultStateDelta: { exposureRisk: 20, priestRedemption: 10 },
    defaultFlagUpdates: { confessedIdentity: true },
    endingKey: "redeemed",
  },
  throne_deceive: {
    id: "throne_deceive",
    sceneId: "act5_throne",
    label: "装到底宣称魔王已被暗中斩杀",
    category: "deceive",
    description: "指着空王座斩钉截铁表示魔王已被你提前消灭，大功告成。",
    defaultStateDelta: { exposureRisk: -5, mageEvidence: 10 },
    endingKey: "perfectSpy",
  },
  throne_blame: {
    id: "throne_blame",
    sceneId: "act5_throne",
    label: "指着维克托宣称他才是新魔王",
    category: "bribe",
    description: "在甩锅维克托的前提下，把一切罪名扣给脑补副官。",
    defaultStateDelta: { thiefLeverage: -5 },
    defaultFlagUpdates: { betrayedVictor: true },
    endingKey: "victorBlamed",
  },
  throne_absurd: {
    id: "throne_absurd",
    sceneId: "act5_throne",
    label: "宣布魔王城改建为主题乐园开业",
    category: "absurd",
    description: "掏出商业计划书请勇者队伍入股魔王城主题乐园。",
    defaultStateDelta: { butterflyDeviation: 30 },
    endingKey: "absurdAscension",
  },
};
